language: node_js

node_js:
  - "7"
  - "6"
  - "5"
  - "4"

install:
  - yarn install

script:
  - npm test
  - npm run report-coverage

after_success:
  - cat ./coverage/coverage-final.json | ./node_modules/codecov.io/bin/codecov.io.js
